In [2]:
#Importing libraries
import pyarrow.parquet as pq
import polars as pl
import os

In [3]:
#Carregando dados na memória
default_path = "C:/Users/Italo/Desktop/UERJ/2026.1/cibersecurity/cybersecurity-uerj-2026-1"
parquet_path = os.path.join(default_path, "final-project/db/dnn.parquet")
print(parquet_path)
tabela_arrow = pq.read_table(parquet_path)
df = pl.from_arrow(tabela_arrow)

C:/Users/Italo/Desktop/UERJ/2026.1/cibersecurity/cybersecurity-uerj-2026-1\final-project/db/dnn.parquet

In [6]:
df.show(20)

frame.time,ip.src_host,ip.dst_host,arp.dst.proto_ipv4,arp.opcode,arp.hw.size,arp.src.proto_ipv4,icmp.checksum,icmp.seq_le,icmp.transmit_timestamp,icmp.unused,http.file_data,http.content_length,http.request.uri.query,http.request.method,http.referer,http.request.full_uri,http.request.version,http.response,http.tls_port,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.connection.fin,tcp.connection.rst,tcp.connection.syn,tcp.connection.synack,tcp.dstport,tcp.flags,tcp.flags.ack,tcp.len,tcp.options,tcp.payload,tcp.seq,tcp.srcport,udp.port,udp.stream,udp.time_delta,dns.qry.name,dns.qry.name.len,dns.qry.qu,dns.qry.type,dns.retransmission,dns.retransmit_request,dns.retransmit_request_in,mqtt.conack.flags,mqtt.conflag.cleansess,mqtt.conflags,mqtt.hdrflags,mqtt.len,mqtt.msg_decoded_as,mqtt.msg,mqtt.msgtype,mqtt.proto_len,mqtt.protoname,mqtt.topic,mqtt.topic_len,mqtt.ver,mbtcp.len,mbtcp.trans_id,mbtcp.unit_id,Attack_label,Attack_type
str,str,str,str,f64,f64,str,f64,f64,f64,f64,str,f64,str,str,str,str,str,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,str,str,f64,str,f64,f64,f64,f64,str,f64,f64,f64,f64,f64,str,f64,f64,f64,f64,f64,str,f64,f64,str,str,f64,f64,f64,f64,f64,i64,str
""" 2021 11:44:10.081753000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,3.1533e9,47892.0,0.0,0.0,0.0,1.0,64855.0,18.0,1.0,0.0,"""020405b40101040201030307""","""0""",0.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.162218000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,3.44794516e8,16077.0,0.0,0.0,0.0,0.0,1883.0,24.0,1.0,14.0,"""0""","""100c00044d5154540402003c0000""",1.0,"""64855.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",1.0,2.0,16.0,12.0,0.0,"""0""",1.0,4.0,"""MQTT""","""0""",0.0,4.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.162271000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,15.0,3.1533e9,62675.0,0.0,0.0,0.0,0.0,64855.0,16.0,1.0,0.0,"""0""","""0""",1.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.162641000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,15.0,3.1533e9,54469.0,0.0,0.0,0.0,0.0,64855.0,24.0,1.0,4.0,"""0""","""20020000""",1.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0x00000000""",0.0,0.0,32.0,2.0,0.0,"""0""",2.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.166132000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,5.0,3.4479452e8,53812.0,0.0,0.0,0.0,0.0,1883.0,24.0,1.0,41.0,"""0""","""3027001854656d7065726174757265…",15.0,"""64855.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,48.0,39.0,0.0,"""32342e36382037362e34320d0a""",3.0,0.0,"""0""","""Temperature_and_Humidity""",24.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.166159000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,56.0,3.1533e9,62630.0,0.0,0.0,0.0,0.0,64855.0,16.0,1.0,0.0,"""0""","""0""",5.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.166968000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,5.0,3.4479452e8,5264.0,1.0,0.0,0.0,0.0,1883.0,25.0,1.0,2.0,"""0""","""e000""",56.0,"""64855.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,224.0,0.0,0.0,"""0""",14.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.167072000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,59.0,3.1533e9,62626.0,1.0,0.0,0.0,0.0,64855.0,17.0,1.0,0.0,"""0""","""0""",5.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.169612000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,0.0,0.0,158.0,0.0,0.0,1.0,0.0,1883.0,2.0,0.0,0.0,"""020405b40103030801010402""","""0""",0.0,"""64856.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.169644000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,3.2943e9,20969.0,0.0,0.0,0.0,1.0,64856.0,18.0,1.0,0.0,"""020405b40101040201030307""","""0""",0.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.172635000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,1.0455e9,54689.0,0.0,0.0,0.0,0.0,1883.0,24.0,1.0,14.0,"""0""","""100c00044d5154540402003c0000""",1.0,"""64856.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",1.0,2.0,16.0,12.0,0.0,"""0""",1.0,4.0,"""MQTT""","""0""",0.0,4.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.172672000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,15.0,3.2943e9,35752.0,0.0,0.0,0.0,0.0,64856.0,16.0,1.0,0.0,"""0""","""0""",1.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.172995000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,15.0,3.2943e9,27546.0,0.0,0.0,0.0,0.0,64856.0,24.0,1.0,4.0,"""0""","""20020000""",1.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0x00000000""",0.0,0.0,32.0,2.0,0.0,"""0""",2.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.173409000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,3.44794516e8,62678.0,0.0,0.0,0.0,0.0,1883.0,16.0,1.0,0.0,"""0""","""0""",1.0,"""64855.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.173434000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,59.0,3.1533e9,62626.0,0.0,0.0,0.0,0.0,64855.0,16.0,1.0,0.0,"""0""","""0""",6.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.173605000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,6.0,3.44794521e8,62615.0,0.0,0.0,0.0,0.0,1883.0,16.0,1.0,0.0,"""0""","""0""",59.0,"""64855.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.173639000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,1.0,1.0455e9,35755.0,0.0,0.0,0.0,0.0,1883.0,16.0,1.0,0.0,"""0""","""0""",1.0,"""64856.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.173654000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,15.0,3.2943e9,35748.0,0.0,0.0,0.0,0.0,64856.0,16.0,1.0,0.0,"""0""","""0""",5.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.176505000 ""","""192.168.0.101""","""192.168.0.128""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,5.0,1.0455e9,26889.0,0.0,0.0,0.0,0.0,1883.0,24.0,1.0,41.0,"""0""","""3027001854656d7065726174757265…",15.0,"""64856.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,48.0,39.0,0.0,"""32342e36382037362e34320d0a""",3.0,0.0,"""0""","""Temperature_and_Humidity""",24.0,0.0,0.0,0.0,0.0,0,"""Normal"""
""" 2021 11:44:10.176556000 ""","""192.168.0.128""","""192.168.0.101""","""0""",0.0,0.0,"""0""",0.0,0.0,0.0,0.0,"""0.0""",0.0,"""0.0""","""0.0""","""0.0""","""0.0""","""0.0""",0.0,0.0,56.0,3.2943e9,35707.0,0.0,0.0,0.0,0.0,64856.0,16.0,1.0,0.0,"""0""","""0""",5.0,"""1883.0""",0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,0.0,0.0,0.0,"""0""",0.0,0.0,"""0""","""0""",0.0,0.0,0.0,0.0,0.0,0,"""Normal"""

In [5]:
#Dropando colunas do dataset
drop_columns = [
    "frame.time", 
    "ip.src_host", 
    "ip.dst_host", 
    "arp.dst.proto_ipv4", 
    "arp.opcode", 
    "arp.hw.size", 
    "arp.dst.proto_ipv4", 
    "arp.src.proto_ipv4", 
    "icmp.checksum", 
    "icmp.seq_le",
    "icmp.transmit_timestamp", 
    "icmp.unused", 
    "http.file_data", #Ponderar se deixar ou não
    "http.request.full_uri",
    "http.referer",
    "http.request.uri.query",
    "http.request.version",
    "http.tls_port",
    "tcp.dstport",
    "tcp.options",
    "tcp.seq",
    "tcp.srcport",
    "udp.port",
    "udp.stream",
    "udp.time_delta",
    "dns.qry.type",
    "dns.retransmission",
    "mqtt.conack.flags",
    "mqtt.msg_decoded_as",
    "mqtt.msg",
    "mqtt.topic"
]


df_revitalized = df.drop(drop_columns)
df_revitalized.head(20)

shape: (20, 33)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ http.conte ┆ http.requ ┆ http.resp ┆ tcp.ack ┆ … ┆ mbtcp.tra ┆ mbtcp.uni ┆ Attack_la ┆ Attack_ty │
│ nt_length  ┆ est.metho ┆ onse      ┆ ---     ┆   ┆ ns_id     ┆ t_id      ┆ bel       ┆ pe        │
│ ---        ┆ d         ┆ ---       ┆ f64     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ ---       ┆ f64       ┆         ┆   ┆ f64       ┆ f64       ┆ i64       ┆ str       │
│            ┆ str       ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 1.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 1.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 15.0    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 15.0    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 5.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ …          ┆ …         ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 6.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 1.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 15.0    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 5.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
│ 0.0        ┆ 0.0       ┆ 0.0       ┆ 56.0    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ Normal    │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [70]:
df.group_by("mbtcp.unit_id", "Attack_label").agg(pl.len().alias("count")).sort("count", descending=True)

shape: (7, 3)
┌───────────────┬──────────────┬─────────┐
│ mbtcp.unit_id ┆ Attack_label ┆ count   │
│ ---           ┆ ---          ┆ ---     │
│ f64           ┆ i64          ┆ u32     │
╞═══════════════╪══════════════╪═════════╡
│ 0.0           ┆ 0            ┆ 1615493 │
│ 0.0           ┆ 1            ┆ 603558  │
│ 1.0           ┆ 0            ┆ 116     │
│ 2.0           ┆ 0            ┆ 22      │
│ 3.0           ┆ 0            ┆ 5       │
│ 4.0           ┆ 0            ┆ 4       │
│ 6.0           ┆ 0            ┆ 3       │
└───────────────┴──────────────┴─────────┘

Normalizando dados do dataset

In [ ]:
#Normalizar coluna de content_length do HTTP

#Features importantes: 
# - http.request.method
# - http.content_length 
# - tcp.ack



# Min-Max http.content_length
df = df.with_columns(
    ((pl.col("http.content_length") - pl.col("http.content_length").min()) / 
     (pl.col("http.content_length").max() - pl.col("http.content_length").min())).alias("http.content_length_normalized")
)


# Min-Max http.content_length
df = df.with_columns(
    ((pl.col("tcp.ack") - pl.col("tcp.ack").min()) / 
     (pl.col("tcp.ack").max() - pl.col("tcp.ack").min())).alias("tcp.ack_normalized")
)

# Min-Max http.content_length
df = df.with_columns(
    ((pl.col("tcp.ack_raw") - pl.col("tcp.ack_raw").min()) / 
     (pl.col("tcp.ack_raw").max() - pl.col("tcp.ack_raw").min())).alias("tcp.ack_raw_normalized")
)

# Min-Max http.content_length
df = df.with_columns(
    ((pl.col("tcp.checksum") - pl.col("tcp.checksum").min()) / 
     (pl.col("tcp.checksum").max() - pl.col("tcp.checksum").min())).alias("tcp.checksum_normalized")
)


df = df.with_columns(
    ((pl.col("tcp.len") - pl.col("tcp.len").min()) / 
     (pl.col("tcp.len").max() - pl.col("tcp.len").min())).alias("tcp.checksum_normalized")
)



df = df.with_columns(
    pl.when(pl.col("tcp.payload") != 0)
      .then(pl.lit(0))
      .otherwise(pl.lit(1))
      .alias("tcp.payload_norm")
)


df = df.with_columns(
    ((pl.col("dns.qry.name") - pl.col("dns.qry.name").min()) / 
     (pl.col("dns.qry.name").max() - pl.col("dns.qry.name").min())).alias("tcp.checksum_normalized")
)






# 4. (Opcional) Se você precisar devolver o resultado para o PyArrow:
tabela_arrow_final = df_normalizado.to_arrow()

# 5. Salvar o arquivo final de volta em Parquet usando o PyArrow
pq.write_table(tabela_arrow_final, os.path.join("db/seu_arquivo_normalizado.parquet"))

print("Processamento concluído com sucesso!")
print(df_normalizado.head()) # Exibe as primeiras 5 linhas do resultado

C:/Users/Italo/Desktop/UERJ/2026.1/cibersecurity/cybersecurity-uerj-2026-1\final-project/db/dnn.parquet
Processamento concluído com sucesso!
shape: (5, 64)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.tim ┆ ip.src_ho ┆ ip.dst_ho ┆ arp.dst.p ┆ … ┆ mbtcp.uni ┆ Attack_la ┆ Attack_ty ┆ http.con │
│ e         ┆ st        ┆ st        ┆ roto_ipv4 ┆   ┆ t_id      ┆ bel       ┆ pe        ┆ tent_len │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ gth_norm │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ i64       ┆ str       ┆ alized   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021 11:4 ┆ 192.168.0 ┆ 192.168.0 ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ Normal    ┆ 0.0      │
│ 4:10.0817 ┆ .128      ┆ .101      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 53000     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021 11:4 ┆ 192.168.0 ┆ 192.168.0 ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ Normal    ┆ 0.0      │
│ 4:10.1622 ┆ .101      ┆ .128      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18000     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021 11:4 ┆ 192.168.0 ┆ 192.168.0 ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ Normal    ┆ 0.0      │
│ 4:10.1622 ┆ .128      ┆ .101      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 71000     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021 11:4 ┆ 192.168.0 ┆ 192.168.0 ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ Normal    ┆ 0.0      │
│ 4:10.1626 ┆ .128      ┆ .101      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 41000     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021 11:4 ┆ 192.168.0 ┆ 192.168.0 ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ Normal    ┆ 0.0      │
│ 4:10.1661 ┆ .101      ┆ .128      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 32000     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘